### PR TITLE
Bug: Throw exception, when create instance OpenAiProvider (#252)

### LINKED ISSUE #252: Throw exception, when create instance OpenAiProvider
### Describe the bug

I get last version nuget packages tryAGI.OpenAI (2.0.6), because, his .ctor was exteneded to support https parameter, some times ago. Yeah! I need it! Early, I used reflection to get correct behaviour in my case (connect to localhost).
But, when I try create instance OpenAiProvider, I got exception: "System.MissingMethodException: Method not found: 'Void OpenAI.OpenAIClientSettings..ctor(System.String, System.String)'."

### Steps to reproduce the bug

1. Get last version nuget package "tryAGI.OpenAI" (2.0.6)
2. Get last version nuget package "LangChain.Providers.OpenAI" (0.13.1-dev107)
3. Create instance OpenAiProvider

### Expected behavior

_No response_

### Screenshots

_No response_

### NuGet package version

"tryAGI.OpenAI" (2.0.6)
"LangChain.Providers.OpenAI" (0.13.1-dev107)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jekakmail**
I propose a lightweight extension for the OpenAiProvider constructor, by adding an additional parameter with a default value.
Also, I try bumped your OpenAi package to latest. 

Closes #252 

## Summary by CodeRabbit

- **New Features**
	- Enhanced the AI provider to accept an optional custom AI client during initialization, allowing for more flexible integration options.
- **Chores**
	- Updated the AI package to the latest version for improved performance and stability.

### CODE REVIEW

File: src/Providers/OpenAI/src/OpenAiProvider.cs [hunk 1]
```diff
@@ -19,16 +19,18 @@ public class OpenAiProvider : Provider
 
     #region Constructors
```
Comment (HavenDV) [inline src/Providers/OpenAI/src/OpenAiProvider.cs:21]:
```suggestion

    public OpenAiProvider(OpenAIClient openAiClient)
        : base(id: OpenAiConfiguration.SectionName)
    {
        Api = openAiClient ?? throw new ArgumentNullException(nameof(openAiClient));
    }

```

Comment (HavenDV) [reply src/Providers/OpenAI/src/OpenAiProvider.cs:21]: I suggest adding another constructor, for those who need it and it does not use the configuration

Comment (jekakmail) [reply src/Providers/OpenAI/src/OpenAiProvider.cs:21]: In this case, properties from the parent Provider class (ChatSettings, EmbeddingSettings, etc.) will not be initialized because they have an 'init' setter.

Comment (HavenDV) [reply src/Providers/OpenAI/src/OpenAiProvider.cs:21]: Do you mean code like this? It should work with init
```cs
new OpenAiProvider(new OpenAIClient())
{
    ChatSettings = new OpenAiChatSettings()
}
```

Comment (HavenDV) [reply src/Providers/OpenAI/src/OpenAiProvider.cs:21]: But maybe we need to remove init restrictions, it doesn't make much sense to prohibit changes to the provider

Comment (jekakmail) [reply src/Providers/OpenAI/src/OpenAiProvider.cs:21]: > Do you mean code like this? It should work with init
> 
> ```cs
> new OpenAiProvider(new OpenAIClient())
> {
>     ChatSettings = new OpenAiChatSettings()
> }
> ```

Oh... I forgot about that option. I guess in that case, your suggestion will do the trick.

**Comment by HavenDV** [comment]
@all-contributors please add @jekakmail for code

**Comment by HavenDV** [comment]
Thank you very much for your contribution. Please write me your name in discord if you want and I will add you to the list of contrubutors and dev channel discussing development and immediate plans

**Comment by jekakmail** [comment]
> Thank you very much for your contribution. Please write me your name in discord if you want and I will add you to the list of contrubutors and dev channel discussing development and immediate plans

My nickname at discord is "jekakmail". I'm glad to help.

**Comment by HavenDV** [comment]
It seems you are not a member of our channel https://discord.com/invite/Ca2xhfBf3v
